version: "3.7"
services:
  app:
    image: kooldev/node:14
    command: ["yarn", "dev"]
    ports:
      - "3000:3000"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    #  - $HOME/.ssh:/home/kool/.ssh:delegated
    networks:
      - kool_local
      - kool_global

networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
